# Generated by Django 2.2 on 2020-08-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_message',
            field=models.IntegerField(default=0),
        ),
    ]
