# Generated by Django 2.2 on 2020-08-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0004_user_has_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='title', max_length=255),
        ),
    ]
