# Generated by Django 2.2 on 2020-08-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0006_auto_20200812_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/no_avatar.png', upload_to='avatars'),
        ),
    ]
